DataPower<-read.csv("household_power_consumption.txt",header = TRUE,sep=";")
DataPower$Date<-as.character(DataPower$Date)
class(DataPower$Date)
DataPower$Date<-as.Date(DataPower$Date,format = "%d/%m/%Y")
DataPower$DateMonth<-month(DataPower$Date)
DataPower$DateDay<-day(DataPower$Date)
DataPower$DateYear<-year(DataPower$Date)
DataPowerFeb2007<-subset(DataPower,DateMonth==2 & DateYear==2007)
DataPowerFeb2007$Global_active_power<-as.character(DataPowerFeb2007$Global_active_power)
DataPowerFeb2007$Global_active_power<-as.numeric(DataPowerFeb2007$Global_active_power)
DataPowerFeb_1_2_2007<-subset(DataPowerFeb2007,DateDay==1 | DateDay==2)
hist(DataPowerFeb_1_2_2007$Global_active_power,breaks=12,main = "Global Active Power", col = "red", xlab = "Global Active Power (kilowatts)")
dev.copy(png,file="plot1.png",width=480,height=480)
dev.off()