DataPower<-read.csv("household_power_consumption.txt",header = TRUE,sep=";")
DataPower$Date<-as.character(DataPower$Date)
class(DataPower$Date)
DataPower$Date<-as.Date(DataPower$Date,format = "%d/%m/%Y")
DataPower$DateMonth<-month(DataPower$Date)
DataPower$DateDay<-day(DataPower$Date)
DataPower$DateYear<-year(DataPower$Date)
DataPowerFeb2007<-subset(DataPower,DateMonth==2 & DateYear==2007)
DataPowerFeb2007$Global_active_power<-as.character(DataPowerFeb2007$Global_active_power)
DataPowerFeb2007$Global_active_power<-as.numeric(DataPowerFeb2007$Global_active_power)
DataPowerFeb_1_2_2007<-subset(DataPowerFeb2007,DateDay==1 | DateDay==2)
DataPowerFeb_1_2_2007$DateTime<-with(DataPowerFeb_1_2_2007,as.POSIXct(paste(as.character(Date),as.character(Time),format="%Y-%m-%d %H:%M:%S")))
DataPowerFeb_1_2_2007$Sub_metering_1<-as.character(DataPowerFeb_1_2_2007$Sub_metering_1)
DataPowerFeb_1_2_2007$Sub_metering_2<-as.character(DataPowerFeb_1_2_2007$Sub_metering_2)
DataPowerFeb_1_2_2007$Sub_metering_3<-as.character(DataPowerFeb_1_2_2007$Sub_metering_3)
DataPowerFeb_1_2_2007$Sub_metering_3<-as.numeric(DataPowerFeb_1_2_2007$Sub_metering_3)
DataPowerFeb_1_2_2007$Sub_metering_2<-as.numeric(DataPowerFeb_1_2_2007$Sub_metering_2)
DataPowerFeb_1_2_2007$Sub_metering_1<-as.numeric(DataPowerFeb_1_2_2007$Sub_metering_1)
png(filename="plot3.png",width=480,height = 480)
with(DataPowerFeb_1_2_2007, plot(DateTime,Sub_metering_1,type="o",pch=NA,ylim = range(c(Sub_metering_1,Sub_metering_2,Sub_metering_3)),xlab="",ylab="Energy sub metering"))
with(DataPowerFeb_1_2_2007,lines(DateTime,Sub_metering_2,type="o",pch=NA,col="red",ylim = range(c(Sub_metering_1,Sub_metering_2,Sub_metering_3))))
with(DataPowerFeb_1_2_2007,lines(DateTime,Sub_metering_3,type="o",pch=NA,col="blue",ylim = range(c(Sub_metering_1,Sub_metering_2,Sub_metering_3))))
legend('topright', c(names(DataPowerFeb_1_2_2007[7]),names(DataPowerFeb_1_2_2007[8]),names(DataPowerFeb_1_2_2007[9])), col=c('black','red','blue'),lty = 1)
dev.off()