DataPower<-read.csv("household_power_consumption.txt",header = TRUE,sep=";")
DataPower$Date<-as.character(DataPower$Date)
class(DataPower$Date)
DataPower$Date<-as.Date(DataPower$Date,format = "%d/%m/%Y")
DataPower$DateMonth<-month(DataPower$Date)
DataPower$DateDay<-day(DataPower$Date)
DataPower$DateYear<-year(DataPower$Date)
DataPowerFeb2007<-subset(DataPower,DateMonth==2 & DateYear==2007)
DataPowerFeb2007$Global_active_power<-as.character(DataPowerFeb2007$Global_active_power)
DataPowerFeb2007$Global_active_power<-as.numeric(DataPowerFeb2007$Global_active_power)
DataPowerFeb_1_2_2007<-subset(DataPowerFeb2007,DateDay==1 | DateDay==2)
DataPowerFeb_1_2_2007$DateTime<-with(DataPowerFeb_1_2_2007,as.POSIXct(paste(as.character(Date),as.character(Time),format="%Y-%m-%d %H:%M:%S")))
with(DataPowerFeb_1_2_2007, plot(DateTime,Global_active_power,type="o",pch=NA,ylab="Global Active Power (kilowatts)",xlab=""))
dev.copy(png,file="plot2.png",width=480,height=480)
dev.off()